name: iOS App Validation

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-project:
    runs-on: macos-15 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Build for Simulator
        run: |
          xcodebuild build \
            -scheme "ToDo Task" \
            -destination 'generic/platform=iOS Simulator' \
            -quiet
